#!/bin/sh
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Generates font source images.

SCRIPT="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT")"
FIRST_ASCII_GLYPH="32" # space
LAST_ASCII_GLYPH="127" # delete
if [ -z "${MENU_UI}" ]; then
  FGCOLOR="#505050"
  FGCOLOR_DARK="$FGCOLOR"
  BGCOLOR="#ffffff"
  FONT="Noto Sans"
  MARGIN="3"
else
  FGCOLOR="#cccccc"
  FGCOLOR_DARK="#9aa0a6"
  BGCOLOR="#202124"
  FONT="Noto Sans Mono"
  MARGIN="0"
fi

die() {
  echo "ERROR: $*" >&2
  exit 1
}

main() {
  [ "$#" = "1" ] || die "Usage: $0 output_dir"
  local output="$1"
  local txt_dir_regular="$output/regular"
  local txt_dir_dark="$output/dark"
  mkdir -p "$txt_dir_regular"
  mkdir -p "$txt_dir_dark"

  local glyph="$FIRST_ASCII_GLYPH"
  local c=''
  local name=''
  local fontsize=""
  echo "Generating glyph text source..."
  while [[ "$glyph"  != "$LAST_ASCII_GLYPH" ]]; do
    c=$(printf "\x$(printf %x $glyph)")
    name="idx$(printf "%03d" $glyph)_$(printf "%x" $glyph)"
    echo "$c" >"$txt_dir_regular/$name.txt"
    echo "$c" >"$txt_dir_dark/$name-dark.txt"
    glyph=$((glyph + 1))
  done

  [ -n "$FONTSIZE" ] && fontsize="--point=$FONTSIZE"

  echo "Converting glyph images..."

  "$SCRIPT_DIR/text_to_png_svg" --font="$FONT" --color="$FGCOLOR" \
    --bgcolor="$BGCOLOR" --margin="$MARGIN 0" --outdir="$output" \
    $fontsize "$txt_dir_regular/*.txt"

  # MENU_UI needs a different set of fonts with darker colors
  if [ ! -z "${MENU_UI}" ]; then
    "$SCRIPT_DIR/text_to_png_svg" --font="$FONT" \
      --color="$FGCOLOR_DARK" --bgcolor="$BGCOLOR" \
      --margin="$MARGIN 0" --outdir="$output" \
      $fontsize "$txt_dir_dark/*.txt"
  fi
}

set -e
main "$@"
