# ChromeOS firmware bitmap block - board configuration.
#
# name1,name2,...:
#   key1: value ...
#   key2: value ...
#   ...
#
# name: List of board names for this configuration, seperated by comma.
# keys are as follows:
# 'assets_dir': Directory of image resources (icons and diagrams) to be used
#               (default: 'assets').
# 'assets_res': Screen resolution that best fits current assets
#               (default: [1366, 768]).
# 'bad_usb3': Presence of USB3 ports that cannot boot recovery (default: False).
# 'locales': List of locales to include (default: All locales).
# 'panel': Panel Dimension (default: [1366, 768]).
# 'phy_rec': Presence of physical recovery button (default: False, check
#            http://crosbug.com/p/24963).
# 'res': Firmware graphics resolution (default: [1366, 768])
# 'sdcard': Presence of SD/MMC Card Reader that can boot in recovery mode
#           (default: True).
#
# These are all the known locales, sorted more-or-less geograpically
#  en es-419 pt-BR fr es pt-PT ca it de
#  el nl da 'no' sv fi et lv lt ru pl cs sk hu sl sr hr bg ro
#  uk tr iw ar fa hi th vi id fil zh-CN zh-TW ko ja

std:
  # Standard bitmap, for test and development.
  res:      [1366, 768]
  panel:    [1366, 768]
  locales:  [en, ja]

peach_pit:
  # 1366x768, boots recovery image on any SD card or USB ports.
  res:      [1366, 768]
  panel:    [1366, 768]

peach_pi:
  # 1920x1080, boots recovery image on any SD card or USB ports.
  res:      [1920, 1080]
  panel:    [1920, 1080]
  assets_dir: assets2x
  assets_res: [1920, 1080]

snow:
  # 1366x768, and can only boot recovery by SD card or USB2 [not USB3].
  res:      [1366, 768]
  panel:    [1366, 768]
  bad_usb3: True

spring:
  # 1366x768, can only boot recovery by USB. (No card reader, or not able to
  # recover from card reader.)
  res:       [1366, 768]
  panel:     [1366, 768]
  sdcard:    False

falco,peppy,wolf,leon:
  # Using VESA graphics mode 1024x768 (0x0117), streched to 1366x768 panel.
  # With card reader. USB3 ports will run in USB2 mode for recovery boot.
  res:      [1024, 768]
  panel:    [1366, 768]

squawks,glimmer,clapper:
  # Using VESA graphics mode 1024x768 (0x0117), streched to 1366x768 panel.
  # With card reader. All USB ports can boot in recovery mode.
  res:      [1024, 768]
  panel:    [1366, 768]

panther,zako:
  # Using VESA graphics mode 1024x768 (0x0117).
  # A chromebox without built-in panel/keyboard.
  # Assume the display is a modern 16:9 (1920x1080) monitor.
  # With card reader and physical recovery switch.
  res:      [1024, 768]
  panel:    [1920, 1080]
  phy_rec:  True

monroe:
  # Using VESA graphics mode 1024x768 (0x0117).
  # A chromestation with built-in panel, without built-in keyboard.
  # Display is a modern 16:9 (1920x1080) monitor.
  # With physical recovery switch, without card reader.
  res:      [1024, 768]
  panel:    [1920, 1080]
  phy_rec:  True
  sdcard:   False

parrot,butterfly:
  # Using VESA graphics mode 1024x768 (0x0117), streched to 1366x768 panel.
  # Can only boot recovery by USB. (No card reader, or not able to recover
  # from card reader.)
  res:      [1024, 768]
  panel:    [1366, 768]
  sdcard:   False

stout:
  # Using VESA graphics mode 1024x768 (0x0117), streched to 1366x768 panel.
  # Can only boot recovery by USB2 [not USB3]. (No card reader, or not able
  # to recover from card reader.)
  res:      [1024, 768]
  panel:    [1366, 768]
  sdcard:   False
  bad_usb3: True

link:
  # Non-standard Graphics mode 1280x850, with 2560x1700 panel.
  # Can boot recovery by USB and SD card readers.
  # Note its firmware can not contain all default locales so the shipping locale
  # list is specified.
  res:      [1280, 850]
  panel:    [2560, 1700]
  locales: [en, es-419, pt-BR, fr, es, it, de, nl, da, 'no', sv, ko, ja, id, th]

stumpy:
  # There's no standard panel size for Stumpy -- depends on the monitor user has
  # attached. Let's assume it's a modern LCD panel with 1920x1080 dimension.
  # Note its firmware can not contain all default locales so the shipping locale
  # list is specified.
  res:      [800, 600]
  panel:    [1920, 1080]
  locales:  [en, es-419, pt-BR, fr, es, it, de, nl, da, 'no', sv, ko, ja]
  sdcard:   False

lumpy:
  # Lumpy was shipped with old firmware bitmaps and caused its resolution to be
  # 800x600.
  # Note its firmware can not contain all default locales so the shipping locale
  # list is specified.
  res:      [800, 600]
  panel:    [1366, 768]
  locales:  [en, es-419, pt-BR, fr, es, it, de, nl, da, 'no', sv, ko, ja]
