#!/bin/sh
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Generates localized text images

SCRIPT="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT")"
TXT_TO_PNG=$(readlink -f "$SCRIPT_DIR/../text_to_png")
BACKGROUND="$SCRIPT_DIR/../../images/Background.png"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

get_width() {
  local input="$1"
  python -c "import Image; print Image.open('$input').size[0]"
}

do_locale() {
  local locale_dir="$1"
  local max_width="$2"
  local font_size=""
  local locale="$(basename $locale_dir)"
  local file conf entry font
  local outdir="${OUTDIR:-.}"
  [ -n "$FONTSIZE" ] && font_size="--point=$FONTSIZE"

  font="$(sed -nre "s/^$locale: *(.*) *$/\1/p" $SCRIPT_DIR/font.conf)"
  mkdir -p "$outdir/$locale"
  for file in $locale_dir/*.txt; do
    entry="$(basename $file)"
    entry="${entry%%.*}"
    conf="$(sed -nre "s/^$entry: *(.*) *$/\1/p" $SCRIPT_DIR/text.conf)"
    conf="$conf $font_size --outdir=$outdir/$locale"
    $TXT_TO_PNG --lan="$locale" --font="$font" $conf $file
    local output_file="$outdir/$locale/$(basename $file)"
    output_file="${output_file%.*}.png"
    if [ "$(get_width $output_file)" -gt $max_width ]; then
      die "Error: message to long: $entry"
    fi
  done
}

main() {
  [ "$#" -gt "0" ] || die "Usage: $0 locale(s)..."

  local max_width="$(( $(get_width $BACKGROUND) * 4 / 5 ))"
  for locale in "$@"; do
    do_locale "$locale" "$max_width"
  done
}

set -e
main "$@"
